CREATE TABLE IF NOT EXISTS USUARIO(
  NOME VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  USRCOD VARCHAR(10),

  PRIMARY KEY(USRCOD)
);

CREATE TABLE IF NOT EXISTS COMPRA(
  USRCOD VARCHAR(10),
  ENDCOBRA VARCHAR(8),
  ENDENTRG VARCHAR(8),
  CODCRT VARCHAR(16),
  CODCMP VARCHAR(10),

  PRIMARY KEY(CODCMP),
  FOREIGN KEY(USRCOD) REFERENCES USUARIO,
  FOREIGN KEY(ENDCOBRA) REFERENCES ENDERECEO,
  FOREIGN KEY(ENDENTRG) REFERENCES ENDERECO,
  FOREIGN KEY(CODCRT) REFERENCES CARTAO
);

CREATE TABLE IF NOT EXISTS PRODUTO(
  CODBARRA INTEGER,
  TIPO VARCHAR(50),
  PRECO DECIMAL(5,2),
  NOME VARCHAR(15),
  DESCRICAO VARCHAR(50),

  PRIMARY KEY(CODBARRA)
);

CREATE TABLE IF NOT EXISTS PRODCMP(
  CODPROD INTEGER,
  CODCMP VARCHAR(10),
  QTD INTEGER,

  PRIMARY KEY(CODPROD,CODCMP),
  FOREIGN KEY(CODCMP) REFERENCES COMPRA,
  FOREIGN KEY(CODPROD) REFERENCES PRODUTO
);

CREATE TABLE IF NOT EXISTS CARRINHO(
  USRCOD VARCHAR(10),
  CODCARR INTEGER,

  PRIMARY KEY(CODCARR),
  FOREIGN KEY(USRCOD) REFERENCES USUARIO
);

CREATE TABLE IF NOT EXISTS PRODCARR(
  CODBARRA INTEGER,
  CODCARR INTEGER,
  QTD INTEGER,

  PRIMARY KEY(CODBARRA,CODCARR),
  FOREIGN KEY(CODCARR) REFERENCES CARRINHO,
  FOREIGN KEY (CODBARRA) REFERENCES PRODUTO
);

CREATE TABLE IF NOT EXISTS ENDERECO(
  LOGRADOURO VARCHAR(50),
  USRCOD VARCHAR(10),
  CEP VARCHAR(8),
  ESTADO VARCHAR(2),
  MUNICIPIO VARCHAR(15),
  NUMERO INTEGER,

  PRIMARY KEY(CEP, NUMERO),
  FOREIGN KEY(USRCOD) REFERENCES USUARIO
);

CREATE TABLE IF NOT EXISTS CARTAO(
  CODCRT VARCHAR(16) NOT NULL,
  CODVRF VARCHAR(3) NOT NULL,
  VALIDADE VARCHAR(10) NOT NULL,
  TITULAR VARCHAR(25),
  OPERADORA VARCHAR(10),
  BANCO VARCHAR(15),
  USRCOD VARCHAR(10),


  PRIMARY KEY(CODCRT),
  FOREIGN KEY(USRCOD) REFERENCES USUARIO
);
