SELECT
USUARIO.NOME,USUARIO.EMAIL, ENDERECO.LOGRADOURO, ENDERECO.NUMERO, ENDERECO.CEP
FROM USUARIO
INNER JOIN ENDERECO ON USUARIO.USRCOD = ENDERECO.USRCOD;


SELECT
USUARIO.NOME,USUARIO.EMAIL, CARTAO.CODCRT, CARTAO.VALIDADE,
CARTAO.OPERADORA, CARTAO.BANCO, CARTAO.TITULAR, CARTAO.CODVRF
FROM USUARIO
INNER JOIN CARTAO ON USUARIO.USRCOD = CARTAO.USRCOD;
