SELECT
USUARIO.NOME,USUARIO.EMAIL, ENDERECO.LOGRADOURO, ENDERECO.NUMERO, ENDERECO.CEP
FROM USUARIO
INNER JOIN ENDERECO ON USUARIO.USRCOD = ENDERECO.USRCOD
WHERE USUARIO.USRCOD = "7";

SELECT
USUARIO.NOME,USUARIO.EMAIL, CARTAO.CODCRT, CARTAO.VALIDADE,
CARTAO.OPERADORA, CARTAO.BANCO, CARTAO.TITULAR, CARTAO.CODVRF
FROM USUARIO
INNER JOIN CARTAO ON USUARIO.USRCOD = CARTAO.USRCOD
WHERE USUARIO.USRCOD="7";

SELECT
PRODUTO.NOME
FROM PRODCARR
INNER JOIN CARRINHO ON PRODCARR.CODCARR = CARRINHO.CODCARR
INNER JOIN PRODUTO ON  PRODCARR.CODBARRA = PRODUTO.CODBARRA
WHERE CARRINHO.USRCOD = "7";

SELECT
USUARIO.NOME, USUARIO.EMAIL, PRODUTO.NOME, PRODUTO.PRECO, PRODUTO.PRECO*PRODCMP.QTD
FROM COMPRA
INNER JOIN USUARIO ON USUARIO.USRCOD = COMPRA.USRCOD
INNER JOIN PRODCMP ON PRODCMP.CODCMP = COMPRA.CODCMP
INNER JOIN PRODUTO ON PRODUTO.CODBARRA = PRODCMP.CODBARRA
WHERE COMPRA.USRCOD="7";

SELECT COMPRA.VALOR
FROM COMPRA
WHERE COMPRA.USRCOD = "7"

SELECT *
FROM PRODCMP
INNER JOIN PRODUTO ON PRODCMP.CODBARRA = PRODUTO.CODBARRA
INNER JOIN COMPRA  ON PRODCMP.CODCMP   = COMPRA.CODCMP
WHERE COMPRA.USRCOD = "7"
